export interface Product {
  id: string;
  name: string;
  brand: string;
  category: string;
  subcategory: string;
  emoji: string;
  accentColor: string;
  price: string;
  trendScore: number;
  saturationScore: number;
  targetAudience: string;
  description: string;
  problem: string;
  uniqueAngle: string;
  topHooks: string[];
  topAdConcepts: { angle: string; concept: string }[];
  competitorPositioning: string;
  tags: string[];
  monthlySearchVolume: string;
  platforms: string[];
}

export const PRODUCTS: Product[] = [
  // ── SKINCARE ────────────────────────────────────────────────────────
  {
    id: "cerave-moisturizing-cream",
    name: "CeraVe Moisturizing Cream",
    brand: "CeraVe",
    category: "Skincare",
    subcategory: "Moisturizer",
    emoji: "🧴",
    accentColor: "#3B82F6",
    price: "$18",
    trendScore: 72,
    saturationScore: 88,
    targetAudience: "Women 18–45 with dry or sensitive skin, dermatologist-trusting buyers",
    description: "Fragrance-free moisturizer with ceramides and hyaluronic acid. Dermatologist #1 recommended brand.",
    problem: "Dry, tight, flaky skin that won't stay moisturized throughout the day",
    uniqueAngle: "Developed with dermatologists — not just marketed to them",
    topHooks: [
      "Dermatologists keep recommending this $18 cream over $200 ones — here's why",
      "I stopped buying expensive moisturizers the day I found this",
      "The moisturizer that sold out at Target 47 times in one year",
    ],
    topAdConcepts: [
      { angle: "Authority", concept: "Side-by-side with luxury moisturizer, same ingredients, 10x price difference" },
      { angle: "Transformation", concept: "30-day skin barrier repair journey with before/after" },
    ],
    competitorPositioning: "Positioned against Tatcha, La Mer, and drugstore competitors by leading with dermatologist credibility rather than luxury or natural claims.",
    tags: ["moisturizer", "skincare", "ceramides", "dry skin", "sensitive skin", "cerave", "drugstore"],
    monthlySearchVolume: "2.4M",
    platforms: ["TikTok", "Meta", "Pinterest"],
  },
  {
    id: "cosrx-snail-mucin",
    name: "COSRX Snail Mucin Essence",
    brand: "COSRX",
    category: "Skincare",
    subcategory: "Essence",
    emoji: "🐌",
    accentColor: "#8B5CF6",
    price: "$25",
    trendScore: 84,
    saturationScore: 62,
    targetAudience: "K-beauty enthusiasts, women 20–38 interested in glass skin, skincare-curious TikTok users",
    description: "96% snail secretion filtrate essence for brightening and repairing skin barrier.",
    problem: "Dull, uneven skin tone and a damaged skin barrier that other serums can't fix",
    uniqueAngle: "Ingredient-led Korean skincare with a gross-sounding but science-backed hero ingredient",
    topHooks: [
      "I put snail slime on my face every night — my skin has never looked better",
      "The $25 Korean serum that broke the internet for a reason",
      "POV: you're watching this at 2am because your skin is desperate",
    ],
    topAdConcepts: [
      { angle: "Curiosity/Gross-out", concept: "Reveal the ingredient first, let skepticism turn into conversion" },
      { angle: "K-beauty education", concept: "Glass skin routine breakdown featuring snail mucin as the hero step" },
    ],
    competitorPositioning: "Owns the 'strange but effective' K-beauty niche. Leans into the gross factor as a differentiator, not a liability.",
    tags: ["snail mucin", "essence", "kbeauty", "korean skincare", "glass skin", "cosrx", "serum"],
    monthlySearchVolume: "890K",
    platforms: ["TikTok", "YouTube", "Meta"],
  },
  {
    id: "good-molecules-niacinamide",
    name: "Good Molecules Niacinamide Serum",
    brand: "Good Molecules",
    category: "Skincare",
    subcategory: "Serum",
    emoji: "💧",
    accentColor: "#06B6D4",
    price: "$12",
    trendScore: 79,
    saturationScore: 71,
    targetAudience: "Budget-conscious skincare fans, women 18–35 with pores/oiliness concerns",
    description: "10% niacinamide + 1% zinc serum for pore minimizing and oil control. Honest, minimal ingredients.",
    problem: "Large pores, oily skin, and spending too much on trendy serums that don't work",
    uniqueAngle: "Same active ingredients as luxury serums at a fraction of the cost — transparency is the brand",
    topHooks: [
      "This $12 serum has the same niacinamide percentage as serums 10x the price",
      "Good Molecules is what happens when you remove the marketing budget and just make a good product",
      "I switched from a $90 pore serum to this and my skin didn't notice the difference",
    ],
    topAdConcepts: [
      { angle: "Price comparison", concept: "Ingredient label comparison with The Ordinary and Paula's Choice" },
      { angle: "No-BS brand story", concept: "Founder talking about why most skincare markup is unjustifiable" },
    ],
    competitorPositioning: "Competes on radical transparency and value. The brand is the anti-luxury play in a luxury-dominated category.",
    tags: ["niacinamide", "pores", "serum", "oily skin", "budget skincare", "good molecules", "zinc"],
    monthlySearchVolume: "430K",
    platforms: ["TikTok", "Instagram", "Amazon"],
  },
  {
    id: "glow-recipe-watermelon",
    name: "Glow Recipe Watermelon Glow Toner",
    brand: "Glow Recipe",
    category: "Skincare",
    subcategory: "Toner",
    emoji: "🍉",
    accentColor: "#F43F5E",
    price: "$34",
    trendScore: 81,
    saturationScore: 58,
    targetAudience: "Gen Z and millennial women who want skincare that looks good on their bathroom shelf",
    description: "Pore-refining toner with watermelon extract, hyaluronic acid, and AHA/BHA blend.",
    problem: "Dull, congested skin — and boring skincare that doesn't feel like self-care",
    uniqueAngle: "Skincare as a lifestyle aesthetic, not just a routine",
    topHooks: [
      "This is the toner that started the fruit-skincare era — and it still wins",
      "The bottle that launched 1,000 shelfie posts does actually work",
      "Gen Z isn't buying skincare — they're buying the ritual",
    ],
    topAdConcepts: [
      { angle: "Aesthetic/lifestyle", concept: "Slow-motion pour of toner into hands, clean bathroom aesthetic, ASMR vibes" },
      { angle: "Results-first", concept: "Before/after pore closeup with honest 14-day timeline" },
    ],
    competitorPositioning: "Competes on aesthetics and brand identity, not just efficacy. The packaging and ingredient storytelling are the product.",
    tags: ["toner", "watermelon", "glow", "pores", "aesthetic skincare", "glow recipe", "aha bha"],
    monthlySearchVolume: "510K",
    platforms: ["TikTok", "Instagram", "Pinterest"],
  },
  {
    id: "the-ordinary-hyaluronic",
    name: "The Ordinary Hyaluronic Acid 2% + B5",
    brand: "The Ordinary",
    category: "Skincare",
    subcategory: "Serum",
    emoji: "🔬",
    accentColor: "#64748B",
    price: "$9",
    trendScore: 76,
    saturationScore: 82,
    targetAudience: "Ingredient-savvy skincare shoppers, budget-conscious buyers 20–40",
    description: "Multi-weight hyaluronic acid serum with vitamin B5 for surface hydration and plumping.",
    problem: "Dehydrated skin and confusion about which expensive serum to trust",
    uniqueAngle: "Clinical ingredient names, clinical prices — removes all the fluff",
    topHooks: [
      "I spend $9 on my serum and my skin is the most hydrated it's ever been",
      "The Ordinary called out the entire beauty industry — and won",
      "Hyaluronic acid doesn't have to cost $80. Here's proof.",
    ],
    topAdConcepts: [
      { angle: "Industry disruption", concept: "Side-by-side comparison of ingredient lists vs price tags of luxury competitors" },
      { angle: "Educational", concept: "What hyaluronic acid actually does, and why the weight matters" },
    ],
    competitorPositioning: "The anti-luxury skincare brand. Wins on ingredient transparency and trust, loses on prestige.",
    tags: ["hyaluronic acid", "serum", "hydration", "the ordinary", "budget", "vitamin b5", "plumping"],
    monthlySearchVolume: "1.1M",
    platforms: ["TikTok", "Amazon", "Sephora"],
  },
  {
    id: "drunk-elephant-c-firma",
    name: "Drunk Elephant C-Firma Fresh Day Serum",
    brand: "Drunk Elephant",
    category: "Skincare",
    subcategory: "Vitamin C Serum",
    emoji: "🍋",
    accentColor: "#F59E0B",
    price: "$90",
    trendScore: 74,
    saturationScore: 55,
    targetAudience: "Skincare enthusiasts 25–45 who invest in premium routines and follow skinfluencers",
    description: "15% L-ascorbic acid vitamin C serum for brightening, firming, and antioxidant protection.",
    problem: "Dull complexion, hyperpigmentation, and premium brands that look good but underdeliver on actives",
    uniqueAngle: "High-potency actives in a clean, 'biocompatible' formula — the clean beauty and clinical worlds colliding",
    topHooks: [
      "The vitamin C serum dermatologists actually use on themselves",
      "I spent 6 months comparing $9 vs $90 vitamin C — the answer surprised me",
      "Drunk Elephant doesn't run ads. This is why their fans do it for free.",
    ],
    topAdConcepts: [
      { angle: "Premium justification", concept: "Explain why concentration and pH stability matter — earn the $90 price tag" },
      { angle: "Community/cult brand", concept: "User-generated content from loyal fans showing 90-day skin transformations" },
    ],
    competitorPositioning: "Plays in the prestige-but-performance tier. Competes against La Roche-Posay and SkinCeuticals on science, against Tatcha on aesthetics.",
    tags: ["vitamin c", "brightening", "drunk elephant", "serum", "hyperpigmentation", "premium skincare", "antioxidant"],
    monthlySearchVolume: "620K",
    platforms: ["Sephora", "TikTok", "Instagram"],
  },

  // ── SUPPLEMENTS ────────────────────────────────────────────────────
  {
    id: "ag1-athletic-greens",
    name: "AG1 by Athletic Greens",
    brand: "Athletic Greens",
    category: "Supplements",
    subcategory: "Greens Powder",
    emoji: "🌿",
    accentColor: "#10B981",
    price: "$99/mo",
    trendScore: 86,
    saturationScore: 68,
    targetAudience: "Health-optimizing professionals 28–45, podcast listeners, biohackers",
    description: "75-ingredient all-in-one daily nutritional supplement with greens, vitamins, probiotics, and adaptogens.",
    problem: "The overwhelming complexity of taking 10 different supplements and still not feeling optimal",
    uniqueAngle: "The supplement for people who hate supplements — one scoop replaces everything",
    topHooks: [
      "I canceled my 7 subscriptions and replaced them all with this one",
      "Every podcast host I respect takes AG1. I finally tried it.",
      "The supplement industry doesn't want you to know you can simplify to one product",
    ],
    topAdConcepts: [
      { angle: "Simplification", concept: "Show the 8 bottles it replaces next to one AG1 bag — visual payoff" },
      { angle: "Authority transfer", concept: "Lean into podcast sponsorships and trusted voices in health optimization" },
    ],
    competitorPositioning: "Positioned as the premium all-in-one vs Bloom (budget/aesthetic) and Athletic Greens competes on formulation depth and bioavailability.",
    tags: ["greens powder", "athletic greens", "ag1", "supplements", "vitamins", "probiotics", "biohacking"],
    monthlySearchVolume: "740K",
    platforms: ["Podcasts", "YouTube", "Meta"],
  },
  {
    id: "bloom-nutrition-greens",
    name: "Bloom Nutrition Super Greens",
    brand: "Bloom Nutrition",
    category: "Supplements",
    subcategory: "Greens Powder",
    emoji: "💚",
    accentColor: "#22C55E",
    price: "$39",
    trendScore: 91,
    saturationScore: 60,
    targetAudience: "Women 18–30, TikTok-native health enthusiasts, gym-goers who want aesthetics and function",
    description: "Digestive enzyme and greens blend with collagen-boosting antioxidants. Available in 8 flavors.",
    problem: "Greens powders that taste like grass and look bad on camera",
    uniqueAngle: "The greens powder that became a TikTok aesthetic — health meets lifestyle content",
    topHooks: [
      "The greens powder that broke TikTok Shop records in 48 hours",
      "I drink this every morning — but the real reason I bought it was the aesthetic",
      "Bloom went from 0 to $100M by understanding that women buy identity, not just supplements",
    ],
    topAdConcepts: [
      { angle: "TikTok-native aesthetic", concept: "Morning routine GRWM featuring Bloom, pastel kitchen, glass tumbler" },
      { angle: "Flavor-first", concept: "Taste test reaction video with the most surprising flavor" },
    ],
    competitorPositioning: "Directly targets AG1's demographic (women who saw it on podcasts) but wins on flavor, price, and social shareability.",
    tags: ["bloom nutrition", "greens powder", "tiktok", "digestive", "collagen", "women", "flavored greens"],
    monthlySearchVolume: "580K",
    platforms: ["TikTok", "Instagram", "TikTok Shop"],
  },
  {
    id: "vital-proteins-collagen",
    name: "Vital Proteins Collagen Peptides",
    brand: "Vital Proteins",
    category: "Supplements",
    subcategory: "Collagen",
    emoji: "✨",
    accentColor: "#EC4899",
    price: "$47",
    trendScore: 80,
    saturationScore: 72,
    targetAudience: "Women 28–50 focused on skin, hair, nails, and joint health",
    description: "Unflavored grass-fed collagen peptides that dissolve in hot or cold beverages.",
    problem: "Aging skin, thinning hair, and supplements that don't actually absorb into the body",
    uniqueAngle: "Collagen for the health-aware woman who puts it in her morning coffee ritual",
    topHooks: [
      "Jennifer Aniston's morning routine includes this — and now I understand why",
      "I added one scoop to my coffee for 90 days. My dermatologist noticed.",
      "Collagen doesn't work — unless you use this kind",
    ],
    topAdConcepts: [
      { angle: "Morning ritual", concept: "Slow pour into coffee, voiceover about skin benefits — aspirational but real" },
      { angle: "Before/after testimonial", concept: "90-day hair growth and skin transformation with real before/after" },
    ],
    competitorPositioning: "Owns the celebrity-endorsed, lifestyle-integrated collagen tier. Competes against Reserveage and Further Food on sourcing quality.",
    tags: ["collagen", "peptides", "vital proteins", "skin", "hair", "nails", "joints", "coffee"],
    monthlySearchVolume: "920K",
    platforms: ["Amazon", "Meta", "Instagram"],
  },
  {
    id: "four-sigmatic-mushroom",
    name: "Four Sigmatic Mushroom Coffee",
    brand: "Four Sigmatic",
    category: "Supplements",
    subcategory: "Functional Coffee",
    emoji: "🍄",
    accentColor: "#92400E",
    price: "$35",
    trendScore: 82,
    saturationScore: 48,
    targetAudience: "Wellness-curious coffee drinkers 25–45, biohackers, people reducing caffeine",
    description: "Instant coffee blend with Lion's Mane and Chaga mushroom extracts for focus and immunity.",
    problem: "Coffee jitters, afternoon crashes, and a productivity plateau that regular coffee can't fix",
    uniqueAngle: "Functional mushrooms make coffee do more — focus without the crash",
    topHooks: [
      "I switched from 3 coffees to 1 mushroom coffee — my anxiety thanked me",
      "The CEO of this company drank mushroom coffee for 365 days straight. Here's what happened.",
      "Your coffee has one job. This coffee has five.",
    ],
    topAdConcepts: [
      { angle: "Upgrade angle", concept: "Morning comparison: regular coffee routine vs mushroom coffee routine — same effort, different output" },
      { angle: "Skeptic-to-believer", concept: "Person who makes fun of mushroom coffee tries it on camera and can't explain why it works" },
    ],
    competitorPositioning: "Owns the functional coffee intersection. Competes against Ryze on price, against regular coffee on health positioning.",
    tags: ["mushroom coffee", "lion's mane", "chaga", "focus", "functional", "four sigmatic", "instant coffee"],
    monthlySearchVolume: "380K",
    platforms: ["Podcast", "YouTube", "Meta"],
  },
  {
    id: "olly-sleep-gummies",
    name: "Olly Sleep Gummies",
    brand: "Olly",
    category: "Supplements",
    subcategory: "Sleep Aid",
    emoji: "😴",
    accentColor: "#7C3AED",
    price: "$14",
    trendScore: 77,
    saturationScore: 74,
    targetAudience: "Adults 25–55 with occasional sleeplessness, people avoiding prescription sleep aids",
    description: "Melatonin + L-theanine + botanicals gummy sleep supplement. Blackberry Zen flavor.",
    problem: "Lying awake at night, groggy mornings from too much melatonin, and not wanting to take prescription sleep meds",
    uniqueAngle: "The approachable, gummy entry point to sleep supplementation — not intimidating, not prescription",
    topHooks: [
      "I've been taking 10mg melatonin for years. My doctor told me to switch to these instead.",
      "The sleep gummy that works better at 3mg than my old supplement did at 10mg",
      "These sold out at every Walmart near me — I finally found out why",
    ],
    topAdConcepts: [
      { angle: "Doctor recommendation", concept: "Explain why lower-dose melatonin with L-theanine works better than high-dose melatonin alone" },
      { angle: "Routine", concept: "Peaceful nighttime routine ending with two gummies — aspirational calm aesthetic" },
    ],
    competitorPositioning: "Competes against Natrol and ZzzQuil on pharmacy shelves, and against Moon Juice and Ned on wellness shelves. Wins on mainstream accessibility.",
    tags: ["sleep", "melatonin", "gummies", "olly", "l-theanine", "sleep aid", "insomnia"],
    monthlySearchVolume: "660K",
    platforms: ["Amazon", "Meta", "Walmart"],
  },

  // ── FITNESS & WELLNESS ──────────────────────────────────────────────
  {
    id: "theragun-mini",
    name: "Theragun Mini Massage Gun",
    brand: "Therabody",
    category: "Fitness",
    subcategory: "Recovery",
    emoji: "💪",
    accentColor: "#EF4444",
    price: "$199",
    trendScore: 83,
    saturationScore: 65,
    targetAudience: "Active adults 22–50, gym-goers, athletes, people with desk-related muscle tension",
    description: "Pocket-sized percussive therapy device with 3 speeds and 150-minute battery life.",
    problem: "Muscle soreness, tension headaches, and recovery tools that are too bulky to use consistently",
    uniqueAngle: "Therabody's entry-level device — makes premium percussive therapy accessible and portable",
    topHooks: [
      "I've been using a $400 massage gun for 2 years. I switched to this and don't miss it.",
      "The massage gun that fits in my purse changed my recovery game forever",
      "Physical therapists use Theragun. Now you can too for under $200.",
    ],
    topAdConcepts: [
      { angle: "Before/after recovery", concept: "Post-workout tightness treated in 2 minutes with Theragun Mini — real-time relief shown" },
      { angle: "Portability", concept: "Use case montage: desk, gym bag, plane, hotel room — it goes everywhere you go" },
    ],
    competitorPositioning: "Premium brand entering mid-price range. Competes against Hypervolt and LifePro on price, against knockoffs on trust and quality.",
    tags: ["massage gun", "theragun", "recovery", "muscle soreness", "percussive therapy", "portable", "fitness"],
    monthlySearchVolume: "550K",
    platforms: ["Amazon", "TikTok", "Meta"],
  },
  {
    id: "oura-ring",
    name: "Oura Ring Gen 3",
    brand: "Oura",
    category: "Fitness",
    subcategory: "Wearable",
    emoji: "💍",
    accentColor: "#1F2937",
    price: "$299",
    trendScore: 88,
    saturationScore: 42,
    targetAudience: "Health-optimizers 28–50, biohackers, executives, people who hate wearing watches",
    description: "Smart ring tracking sleep, HRV, readiness, and activity. No screen, 7-day battery.",
    problem: "Wrist-based wearables are uncomfortable to sleep in — and sleep tracking is the most important data",
    uniqueAngle: "The most accurate sleep tracker in the world that you forget you're wearing",
    topHooks: [
      "I learned more about my health in 30 days from a ring than in 5 years of Apple Watch data",
      "The Oura Ring told me I was sick before I had symptoms — twice",
      "Biohackers swear by this. After 60 days, I understand why.",
    ],
    topAdConcepts: [
      { angle: "Data revelation", concept: "Show the Oura app revealing surprising sleep/HRV insight that changes a morning decision" },
      { angle: "Invisible tech", concept: "Day in the life where the ring is barely mentioned but drives every health decision" },
    ],
    competitorPositioning: "Competes against Apple Watch and WHOOP. Wins on form factor and sleep accuracy. Loses on real-time display.",
    tags: ["oura ring", "sleep tracker", "biohacking", "hrv", "wearable", "health tracking", "ring"],
    monthlySearchVolume: "490K",
    platforms: ["YouTube", "Podcast", "Meta"],
  },
  {
    id: "stanley-quencher",
    name: "Stanley Quencher Tumbler 40oz",
    brand: "Stanley",
    category: "Fitness",
    subcategory: "Hydration",
    emoji: "🥤",
    accentColor: "#0EA5E9",
    price: "$45",
    trendScore: 94,
    saturationScore: 85,
    targetAudience: "Women 18–40, moms, college students, office workers — the hydration aesthetic crowd",
    description: "40oz insulated stainless steel tumbler with handle, straw, and 7-hour cold retention.",
    problem: "Water bottles that don't fit in cup holders, don't keep drinks cold, and don't match your vibe",
    uniqueAngle: "A $45 water tumbler that became a cultural phenomenon — not just a product",
    topHooks: [
      "The water bottle that sold out in 7 minutes when Target dropped the limited edition color",
      "Stanley went 100 years without going viral. Then one TikTok changed everything.",
      "I tracked down the Costal Pink Stanley and I want to explain why that says something about marketing",
    ],
    topAdConcepts: [
      { angle: "Color drop scarcity", concept: "New colorway reveal with countdown timer — FOMO-driven limited drop mechanics" },
      { angle: "Lifestyle fit", concept: "Stanley living in car cup holder, at gym, in office, at school — it literally fits everywhere" },
    ],
    competitorPositioning: "Competes against YETI and Hydro Flask on quality. Now competes on color releases and identity signaling — a different game entirely.",
    tags: ["stanley", "tumbler", "quencher", "water bottle", "hydration", "tiktok", "aesthetic", "cup"],
    monthlySearchVolume: "3.2M",
    platforms: ["TikTok", "Target", "Meta"],
  },

  // ── TECH & GADGETS ──────────────────────────────────────────────────
  {
    id: "gopro-hero12",
    name: "GoPro Hero 12 Black",
    brand: "GoPro",
    category: "Tech",
    subcategory: "Camera",
    emoji: "📷",
    accentColor: "#1D4ED8",
    price: "$399",
    trendScore: 75,
    saturationScore: 62,
    targetAudience: "Outdoor adventurers 18–40, content creators, sports enthusiasts, travel vloggers",
    description: "5.3K action camera with HyperSmooth 6.0 stabilization, waterproof to 33ft, 27MP photos.",
    problem: "Shaky, low-quality footage from phone cameras that weren't built for action and adventure",
    uniqueAngle: "The professional-grade action camera that turned millions of regular people into content creators",
    topHooks: [
      "This $399 camera has created more viral content than most $5K setups",
      "I've been filming my runs for 3 years. This GoPro made me 40K followers.",
      "GoPro footage has a feeling. Here's what it means for your content.",
    ],
    topAdConcepts: [
      { angle: "Adventure showcase", concept: "Split-screen: boring phone footage vs cinematic GoPro footage of the same moment" },
      { angle: "Creator proof", concept: "Average person with GoPro getting brand deals and viral moments" },
    ],
    competitorPositioning: "Competes against DJI Osmo on stabilization, against phone cameras on adventure-readiness. Owns the action camera identity.",
    tags: ["gopro", "action camera", "4k", "waterproof", "adventure", "vlog", "content creator", "go"],
    monthlySearchVolume: "1.8M",
    platforms: ["YouTube", "Meta", "Amazon"],
  },
  {
    id: "govee-led-lights",
    name: "Govee RGBIC LED Strip Lights",
    brand: "Govee",
    category: "Tech",
    subcategory: "Smart Home Lighting",
    emoji: "🌈",
    accentColor: "#A855F7",
    price: "$35",
    trendScore: 87,
    saturationScore: 78,
    targetAudience: "Gen Z gamers, dorm room decorators, content creators, home office workers 16–30",
    description: "16 million color RGBIC strip lights with music sync, app control, and Alexa/Google integration.",
    problem: "Boring room lighting that kills the vibe for gaming, streaming, or just living in a cool space",
    uniqueAngle: "The LED brand that understood aesthetic content was the product demo",
    topHooks: [
      "I spent $35 and my room looks like it's worth $35K",
      "Every gaming setup, every dorm room, every aesthetic office has these — here's why",
      "Govee became a $1B company because they understood that lighting is identity",
    ],
    topAdConcepts: [
      { angle: "Room transformation", concept: "Before/after room reveal with lights off vs lights on — visual shock" },
      { angle: "Vibe showcase", concept: "Music sync feature in action — lights responding to popular song in real-time" },
    ],
    competitorPositioning: "Competes against Philips Hue on smart home integration, against cheap Amazon strips on quality. Wins on aesthetic and TikTok virality.",
    tags: ["led lights", "govee", "rgb", "smart home", "gaming", "room decor", "tiktok aesthetic", "strip lights"],
    monthlySearchVolume: "720K",
    platforms: ["TikTok", "Amazon", "YouTube"],
  },
  {
    id: "ember-mug",
    name: "Ember Smart Mug 2",
    brand: "Ember",
    category: "Tech",
    subcategory: "Smart Kitchen",
    emoji: "☕",
    accentColor: "#DC2626",
    price: "$149",
    trendScore: 76,
    saturationScore: 44,
    targetAudience: "Coffee enthusiasts 28–50, remote workers, people who keep forgetting their coffee gets cold",
    description: "Temperature-controlled ceramic mug that keeps coffee/tea at your perfect temperature for 80 minutes.",
    problem: "Cold coffee — the universal tragedy of every office worker and work-from-home professional",
    uniqueAngle: "A mug that maintains the perfect sip temperature — not just hot, your exact preferred temperature",
    topHooks: [
      "I didn't know I needed a $149 mug until my wife bought me one",
      "The gift that every coffee drinker says they don't need — until they have it",
      "Ember solved the problem no coffee maker ever addressed",
    ],
    topAdConcepts: [
      { angle: "Gift positioning", concept: "Gifting moment — person opening it skeptically, using it, then ordering one for a friend" },
      { angle: "Pain point", concept: "Show 5 abandoned half-drunk cups of cold coffee, then the Ember solution" },
    ],
    competitorPositioning: "Category creator. No real competitor at this price-quality tier. Competes against thermos mugs on awareness.",
    tags: ["ember mug", "smart mug", "coffee", "temperature control", "gift", "work from home", "tech"],
    monthlySearchVolume: "310K",
    platforms: ["Amazon", "Meta", "Pinterest"],
  },
  {
    id: "levoit-air-purifier",
    name: "Levoit Core 300 Air Purifier",
    brand: "Levoit",
    category: "Tech",
    subcategory: "Home Appliance",
    emoji: "💨",
    accentColor: "#7DD3FC",
    price: "$99",
    trendScore: 81,
    saturationScore: 70,
    targetAudience: "People with allergies/asthma, pet owners, parents of young children, health-conscious homeowners",
    description: "H13 True HEPA air purifier covering 219 sq ft, 3-stage filtration, whisper-quiet 24dB.",
    problem: "Indoor air that's 5x more polluted than outdoor air — and no one told you about it",
    uniqueAngle: "The air purifier that made the brand story about indoor air quality awareness, not just clean air",
    topHooks: [
      "Your indoor air is 5x more polluted than outdoor air. This is the $99 fix.",
      "I got this for my allergies. My Amazon reviews say I changed lives.",
      "The air purifier category exploded after COVID — Levoit owned the moment",
    ],
    topAdConcepts: [
      { angle: "Shocking statistic", concept: "Open with the 5x indoor air pollution stat, then show the Levoit solution" },
      { angle: "Pet owner angle", concept: "Pet dander visible in light beam, purifier running, baby/allergy sufferer breathing easier" },
    ],
    competitorPositioning: "Competes against Dyson and Blueair on premium tier, against Winix and Honeywell on mid-tier. Wins on price-to-HEPA-performance ratio.",
    tags: ["air purifier", "levoit", "hepa", "allergies", "pet dander", "clean air", "home", "asthma"],
    monthlySearchVolume: "590K",
    platforms: ["Amazon", "TikTok", "Meta"],
  },

  // ── HOME & KITCHEN ──────────────────────────────────────────────────
  {
    id: "ninja-air-fryer",
    name: "Ninja Air Fryer XL",
    brand: "Ninja",
    category: "Home",
    subcategory: "Kitchen Appliance",
    emoji: "🍟",
    accentColor: "#1F2937",
    price: "$119",
    trendScore: 78,
    saturationScore: 82,
    targetAudience: "Home cooks 25–55, health-conscious families, meal preppers",
    description: "5.5 Qt air fryer with 4 cooking functions — air fry, roast, reheat, dehydrate.",
    problem: "Craving fried food while trying to eat healthier — and an oven that takes forever to heat up",
    uniqueAngle: "Healthy fried food isn't a contradiction — it's just physics",
    topHooks: [
      "I made french fries with 0 oil. My kids couldn't tell the difference.",
      "The kitchen appliance that actually gets used every single day",
      "Air fryers aren't a trend — they're a lifestyle upgrade that's now permanent",
    ],
    topAdConcepts: [
      { angle: "Health transformation", concept: "Same food, 80% less oil, 5 minutes faster — side-by-side comparison" },
      { angle: "Meal prep UGC", concept: "Weekly meal prep routine entirely using the Ninja air fryer — relatable and aspirational" },
    ],
    competitorPositioning: "Competes against Cosori and Instant Vortex on features-per-dollar. Wins on brand recognition and retail availability.",
    tags: ["air fryer", "ninja", "kitchen", "cooking", "healthy", "meal prep", "appliance", "fried food"],
    monthlySearchVolume: "2.1M",
    platforms: ["Amazon", "TikTok", "Meta"],
  },
  {
    id: "nespresso-vertuo",
    name: "Nespresso Vertuo Plus",
    brand: "Nespresso",
    category: "Home",
    subcategory: "Coffee Machine",
    emoji: "☕",
    accentColor: "#6B21A8",
    price: "$199",
    trendScore: 73,
    saturationScore: 68,
    targetAudience: "Coffee lovers 28–55 who want cafe quality at home without barista complexity",
    description: "Single-serve coffee machine with centrifusion technology. Makes 5 cup sizes from espresso to alto.",
    problem: "Paying $7 for a coffee shop drink you could make better at home in 2 minutes",
    uniqueAngle: "The machine that made premium coffee at home possible without a learning curve",
    topHooks: [
      "I spent $200 on this machine and now spend $0 at coffee shops. Math checks out.",
      "Nespresso is what happens when a coffee brand decides taste should be accessible, not gatekept",
      "Everyone I know with this machine bought one for their parents too",
    ],
    topAdConcepts: [
      { angle: "Financial ROI", concept: "Calculate the annual coffee shop spend saved vs one-time machine investment" },
      { angle: "Morning ritual", concept: "Elegant morning coffee ritual in a beautiful kitchen — aspirational but achievable" },
    ],
    competitorPositioning: "Competes against Keurig on convenience, against real espresso machines on simplicity. Owns the accessible-premium intersection.",
    tags: ["nespresso", "coffee machine", "espresso", "pods", "coffee", "kitchen", "morning routine"],
    monthlySearchVolume: "880K",
    platforms: ["Amazon", "Meta", "Pinterest"],
  },
  {
    id: "pura-diffuser",
    name: "Pura Smart Fragrance Diffuser",
    brand: "Pura",
    category: "Home",
    subcategory: "Fragrance",
    emoji: "🌸",
    accentColor: "#F0ABFC",
    price: "$44",
    trendScore: 83,
    saturationScore: 45,
    targetAudience: "Home fragrance enthusiasts 25–45, interior design-conscious homeowners",
    description: "WiFi-connected diffuser with app-controlled schedules, intensity, and 100+ branded fragrance partnerships.",
    problem: "Candles you forget to light, plug-ins that smell cheap, and never having your home smell exactly how you want",
    uniqueAngle: "Set your home scent on a schedule — the fragrance experience you never knew you could customize",
    topHooks: [
      "My house smells like a $500/night hotel. I spent $44.",
      "Pura has partnerships with every premium candle brand — and you get their scent without the candle",
      "The diffuser that made home fragrance finally feel premium, not plug-in cheap",
    ],
    topAdConcepts: [
      { angle: "Premium comparison", concept: "Walk into the scene of a luxurious-smelling home, reveal it's Pura on a wall" },
      { angle: "App control", concept: "Schedule your home's scent — wake up, come home, wind down — show the app in action" },
    ],
    competitorPositioning: "Competes against Air Wick and Febreze plug-ins on category, against Diptyque on premium. Wins the tech-meets-fragrance position.",
    tags: ["pura", "diffuser", "fragrance", "smart home", "scent", "home decor", "plugin", "candle"],
    monthlySearchVolume: "240K",
    platforms: ["Instagram", "TikTok", "Meta"],
  },
  {
    id: "weighted-blanket",
    name: "YnM Weighted Blanket",
    brand: "YnM",
    category: "Home",
    subcategory: "Bedding",
    emoji: "🛏️",
    accentColor: "#374151",
    price: "$55",
    trendScore: 71,
    saturationScore: 77,
    targetAudience: "Anxiety sufferers, people with sleep issues, parents buying for kids with sensory needs",
    description: "7-layer breathable cotton weighted blanket with glass beads, available in 5 to 30 lbs.",
    problem: "Racing thoughts at night, anxiety that won't let you sleep, and waking up exhausted",
    uniqueAngle: "Deep pressure stimulation in a blanket — the anxiety solution that doesn't require a prescription",
    topHooks: [
      "My therapist suggested a weighted blanket. I thought it was ridiculous. I was wrong.",
      "Deep pressure therapy is clinically studied. This is the $55 version.",
      "I sleep with 20 pounds on me now and I've never slept better in my life",
    ],
    topAdConcepts: [
      { angle: "Anxiety/sleep education", concept: "Explain the science of deep pressure therapy, position the blanket as the practical tool" },
      { angle: "Skeptic conversion", concept: "Person who thought it was a gimmick becomes a believer after one night" },
    ],
    competitorPositioning: "Budget-to-mid tier in the weighted blanket category. Competes against Bearaby on premium, against Degrees of Comfort on features.",
    tags: ["weighted blanket", "sleep", "anxiety", "ynm", "sensory", "deep pressure", "bedding"],
    monthlySearchVolume: "610K",
    platforms: ["Amazon", "Meta", "Pinterest"],
  },

  // ── BEAUTY & MAKEUP ─────────────────────────────────────────────────
  {
    id: "rare-beauty-blush",
    name: "Rare Beauty Soft Pinch Liquid Blush",
    brand: "Rare Beauty",
    category: "Beauty",
    subcategory: "Blush",
    emoji: "🩷",
    accentColor: "#FB7185",
    price: "$23",
    trendScore: 93,
    saturationScore: 52,
    targetAudience: "Beauty enthusiasts 16–35, Selena Gomez fans, TikTok beauty community",
    description: "Buildable liquid blush with a natural flush finish. 1 drop covers both cheeks. 12 shades.",
    problem: "Powder blushes that look cakey or fade by noon — and finding a formula that actually looks like a real flush",
    uniqueAngle: "One drop does the job — the most viral beauty product of the decade",
    topHooks: [
      "One drop of this blush and I look like I just ran 5 miles in the best possible way",
      "Rare Beauty did $70M in revenue in its first year. The blush is why.",
      "Selena Gomez created the most viral beauty product by accident — and it changed the industry",
    ],
    topAdConcepts: [
      { angle: "Application shock", concept: "Show one tiny drop looking like too much, blended to a perfect natural flush — the transformation is the ad" },
      { angle: "Shade inclusivity", concept: "12 shades, every skin tone represented, every result gorgeous" },
    ],
    competitorPositioning: "Competes against NARS and Charlotte Tilbury liquid blushes. Wins on price, accessibility, and Selena's authentic brand story.",
    tags: ["rare beauty", "blush", "selena gomez", "liquid blush", "tiktok beauty", "makeup", "viral"],
    monthlySearchVolume: "1.4M",
    platforms: ["TikTok", "Sephora", "Instagram"],
  },
  {
    id: "charlotte-tilbury-filter",
    name: "Charlotte Tilbury Flawless Filter",
    brand: "Charlotte Tilbury",
    category: "Beauty",
    subcategory: "Primer/Complexion",
    emoji: "✨",
    accentColor: "#F9A8D4",
    price: "$49",
    trendScore: 82,
    saturationScore: 60,
    targetAudience: "Makeup-wearing women 22–45 who want a filtered, glowy skin effect",
    description: "Complexion booster that works as primer, highlighter, or can be mixed with foundation for a luminous finish.",
    problem: "Wanting the blurred, filtered camera look in real life — without a heavy filter or full foundation",
    uniqueAngle: "The Flawless Filter isn't a category — it created its own",
    topHooks: [
      "This is the product that made me look like an Instagram filter in real life",
      "Charlotte Tilbury built a billion-dollar brand. The Flawless Filter is why.",
      "I wear this alone. I wear this under foundation. I wear this everywhere.",
    ],
    topAdConcepts: [
      { angle: "Before/after glow", concept: "Bare skin vs Flawless Filter — the glow difference in 3 seconds" },
      { angle: "Multi-use versatility", concept: "5 ways to use one product: morning GRWM showing all applications" },
    ],
    competitorPositioning: "Owns the 'skin finish' category. No direct competitor has the same cultural positioning. Charlotte Tilbury is aspirational luxury accessible at Sephora.",
    tags: ["charlotte tilbury", "flawless filter", "primer", "glow", "highlighter", "complexion", "makeup"],
    monthlySearchVolume: "760K",
    platforms: ["TikTok", "Sephora", "YouTube"],
  },
  {
    id: "dyson-airwrap",
    name: "Dyson Airwrap Multi-Styler",
    brand: "Dyson",
    category: "Beauty",
    subcategory: "Hair Tool",
    emoji: "💇",
    accentColor: "#F97316",
    price: "$599",
    trendScore: 88,
    saturationScore: 55,
    targetAudience: "Women 22–50 who invest in hair tools, content creators, beauty enthusiasts",
    description: "Air-powered multi-styler that curls, waves, smooths, and volumizes using the Coanda effect — no extreme heat.",
    problem: "Heat damage from traditional curling irons, and styling tools that take 45 minutes to achieve a look that falls out in 2 hours",
    uniqueAngle: "The only styling tool that styles with air — less heat, less damage, better results",
    topHooks: [
      "I returned my Dyson Airwrap after one week. Then I bought it again. Here's the honest review.",
      "The $599 hair tool that made everyone else's $50 curling iron feel embarrassing",
      "Dyson engineers a vacuum. Then they engineer the most viral hair tool in history. Same physics.",
    ],
    topAdConcepts: [
      { angle: "Heat damage education", concept: "Show hair damage under microscope from traditional heat vs Airwrap results" },
      { angle: "Real-time styling", concept: "Time-lapse of full blowout/curl routine in 12 minutes — faster than traditional tools" },
    ],
    competitorPositioning: "Category creator for air-styling. Competes against T3 and ghd on luxury heat tools. Wins on innovation story and social proof.",
    tags: ["dyson airwrap", "hair tool", "styling", "curls", "blowout", "heat damage", "coanda", "dyson"],
    monthlySearchVolume: "2.8M",
    platforms: ["TikTok", "Instagram", "YouTube"],
  },
  {
    id: "sol-de-janeiro",
    name: "Sol de Janeiro Brazilian Crush Body Mist",
    brand: "Sol de Janeiro",
    category: "Beauty",
    subcategory: "Body Fragrance",
    emoji: "🌺",
    accentColor: "#FBBF24",
    price: "$38",
    trendScore: 90,
    saturationScore: 50,
    targetAudience: "Women 16–35, fragrance lovers, TikTok beauty community, summer-lifestyle buyers",
    description: "Whipped, lotion-like body mist in Cheirosa 62 scent — pistachio and salted caramel.",
    problem: "Perfumes that don't last on skin and body sprays that smell cheap",
    uniqueAngle: "The $38 body mist that broke Sephora's website and sold out across the country",
    topHooks: [
      "People keep asking what I smell like. It's $38 and I won't stop telling everyone.",
      "Sol de Janeiro Cheirosa 62 is the scent of summer 2023, 2024, and probably 2025",
      "Sephora had to limit purchases to 2 per person. For a body mist.",
    ],
    topAdConcepts: [
      { angle: "Scent storytelling", concept: "Visualize the pistachio/salted caramel scent through a slow-motion summer scene" },
      { angle: "Compliment magnet", concept: "UGC of real people describing the compliments they get from wearing it" },
    ],
    competitorPositioning: "Competes against Bath & Body Works on accessible fragrance, against Maison Margiela on prestige. Wins on social shareability.",
    tags: ["sol de janeiro", "body mist", "fragrance", "sephora", "cheirosa", "tiktok", "summer", "scent"],
    monthlySearchVolume: "1.1M",
    platforms: ["TikTok", "Sephora", "Instagram"],
  },

  // ── FOOD & DRINK ────────────────────────────────────────────────────
  {
    id: "liquid-death",
    name: "Liquid Death Mountain Water",
    brand: "Liquid Death",
    category: "Food & Drink",
    subcategory: "Water",
    emoji: "💀",
    accentColor: "#1F2937",
    price: "$2/can",
    trendScore: 95,
    saturationScore: 38,
    targetAudience: "Younger adults 18–35, festival-goers, people who want to look cool while staying sober",
    description: "Austrian Alps still or sparkling mountain water in a tallboy can. The world's fastest-growing beverage brand.",
    problem: "Water is boring, but energy drinks and soda are bad for you — and there's no cool-looking healthy option",
    uniqueAngle: "The marketing is the product. Water in a beer can with a metal brand.",
    topHooks: [
      "Liquid Death is a marketing masterclass disguised as water",
      "They put mountain water in a beer can and built a $700M company. The lesson is insane.",
      "The only water brand with a mailing list, merch, and a hardcore fanbase",
    ],
    topAdConcepts: [
      { angle: "Brand satire", concept: "Over-the-top metal/extreme commercial for something as innocent as water — the irony is the joke" },
      { angle: "Social proof", concept: "Festival, concert, gym — Liquid Death everywhere normal people would reach for a beer" },
    ],
    competitorPositioning: "Competes against Evian and Smartwater on premium water. Really competes against energy drinks and beer on social occasion. Wins on identity.",
    tags: ["liquid death", "water", "canned water", "brand", "marketing", "sparkling water", "tiktok"],
    monthlySearchVolume: "580K",
    platforms: ["TikTok", "Instagram", "DTC"],
  },
  {
    id: "olipop-soda",
    name: "Olipop Prebiotic Soda",
    brand: "Olipop",
    category: "Food & Drink",
    subcategory: "Functional Beverage",
    emoji: "🥤",
    accentColor: "#84CC16",
    price: "$3/can",
    trendScore: 89,
    saturationScore: 55,
    targetAudience: "Health-conscious soda lovers 22–40, gut health enthusiasts, parents reducing sugar for kids",
    description: "Gut-healthy soda with 9g prebiotic fiber, 45 calories, and nostalgic flavors like Vintage Cola and Strawberry Vanilla.",
    problem: "Soda you love but can't justify — and gut health drinks that taste like medicine",
    uniqueAngle: "The soda that's actually good for your gut — not good for a health drink, actually good",
    topHooks: [
      "I gave up soda for 3 years. Then someone handed me an Olipop.",
      "The soda that your gut microbiome will actually thank you for",
      "Olipop is proof that healthy and delicious stopped being opposites",
    ],
    topAdConcepts: [
      { angle: "Nostalgia + health", concept: "Old-school soda aesthetic (50s diner vibes) with a modern gut health overlay" },
      { angle: "Taste test conversion", concept: "Person who 'doesn't drink health drinks' tries Olipop — reaction video" },
    ],
    competitorPositioning: "Competes against Poppi on the prebiotic soda shelf. Competes against Coke on occasions. Wins on flavor variety and functional story.",
    tags: ["olipop", "prebiotic soda", "gut health", "functional beverage", "soda", "fiber", "healthy"],
    monthlySearchVolume: "420K",
    platforms: ["TikTok", "Whole Foods", "Meta"],
  },
  {
    id: "magic-spoon-cereal",
    name: "Magic Spoon Protein Cereal",
    brand: "Magic Spoon",
    category: "Food & Drink",
    subcategory: "Cereal",
    emoji: "🥣",
    accentColor: "#EC4899",
    price: "$13/box",
    trendScore: 78,
    saturationScore: 52,
    targetAudience: "Health-conscious adults 22–40 who grew up on sugary cereal and miss it",
    description: "High-protein, grain-free, keto-friendly cereal in flavors like Fruity, Cocoa, and Frosted. 13g protein, 3g sugar.",
    problem: "Giving up childhood cereal because adult nutrition requirements made it off-limits",
    uniqueAngle: "Childhood nostalgia, adult macros — the cereal that shouldn't exist but does",
    topHooks: [
      "I ate Fruity Pebbles for breakfast every day for a decade. Now I eat these instead.",
      "13g protein, 3g sugar — in a bowl of cereal that tastes like childhood",
      "The DTC cereal brand that outsells legacy brands at $13 a box",
    ],
    topAdConcepts: [
      { angle: "Nostalgia trigger", concept: "Old cereal commercial parody with new health stats overlay — ironic and effective" },
      { angle: "Macro reveal", concept: "Show standard cereal nutrition label vs Magic Spoon — the comparison does the work" },
    ],
    competitorPositioning: "Competes against Krave and regular cereals on nostalgia. Competes against Quest on protein. Owns the 'grown-up sugary cereal' space.",
    tags: ["magic spoon", "protein cereal", "keto", "healthy cereal", "high protein", "grain free", "breakfast"],
    monthlySearchVolume: "290K",
    platforms: ["DTC", "Meta", "Podcast"],
  },

  // ── PET ──────────────────────────────────────────────────────────────
  {
    id: "furbo-camera",
    name: "Furbo 360° Dog Camera",
    brand: "Furbo",
    category: "Pet",
    subcategory: "Pet Tech",
    emoji: "🐕",
    accentColor: "#F59E0B",
    price: "$169",
    trendScore: 76,
    saturationScore: 48,
    targetAudience: "Dog owners 25–50 who work outside the home and experience pet separation anxiety",
    description: "360° rotating dog camera with 2-way audio, treat tossing, and AI dog activity alerts.",
    problem: "The guilt and anxiety of leaving your dog home alone all day without knowing if they're okay",
    uniqueAngle: "A camera that lets you talk to and treat your dog from work — eliminates pet owner guilt",
    topHooks: [
      "I watched my dog wait by the door for 3 hours. Then I got a Furbo.",
      "The product that made 'separation anxiety' a purchase trigger for millions of pet owners",
      "I toss my dog a treat from my work laptop. It's chaotic and I love it.",
    ],
    topAdConcepts: [
      { angle: "Emotional hook", concept: "Show dog waiting by the door (guilt trigger), then owner using Furbo to check in — relief payoff" },
      { angle: "Treat toss demo", concept: "Dog goes absolutely crazy for the treat toss — pure joy, immediate desire" },
    ],
    competitorPositioning: "Competes against Petcube on features. Wins on the treat toss mechanic and emotional brand story around dog separation.",
    tags: ["furbo", "dog camera", "pet camera", "treat toss", "dog", "pet tech", "separation anxiety"],
    monthlySearchVolume: "220K",
    platforms: ["Amazon", "Meta", "TikTok"],
  },
  {
    id: "chomchom-roller",
    name: "ChomChom Pet Hair Roller",
    brand: "ChomChom",
    category: "Pet",
    subcategory: "Pet Cleaning",
    emoji: "🐾",
    accentColor: "#10B981",
    price: "$30",
    trendScore: 81,
    saturationScore: 55,
    targetAudience: "Pet owners with shedding dogs or cats, couch-loving pet families",
    description: "Reusable, self-cleaning pet hair roller — no tape or batteries needed. Works in both directions.",
    problem: "Pet hair on absolutely everything — couches, clothes, car seats — and lint rollers that run out instantly",
    uniqueAngle: "The reusable pet hair solution that outperforms every tape roller and costs the same per year",
    topHooks: [
      "I spent $30 five years ago. I haven't bought another pet hair product since.",
      "The ChomChom roller is the #1 pet product on Amazon — 6 years running. Here's a demo.",
      "My golden retriever sheds enough to build another dog each week. This is how I cope.",
    ],
    topAdConcepts: [
      { angle: "Demo-first", concept: "Show a hair-covered couch, one pass of the ChomChom, immediate transformation" },
      { angle: "Repeat purchase elimination", concept: "Show receipts for 3 years of lint rollers vs one ChomChom purchase" },
    ],
    competitorPositioning: "Competes against Scotch and Evercare lint rollers. Wins on reusability, environmental angle, and product effectiveness.",
    tags: ["chomchom", "pet hair", "lint roller", "dog hair", "cat hair", "couch", "reusable", "pet"],
    monthlySearchVolume: "390K",
    platforms: ["Amazon", "TikTok", "Meta"],
  },

  // ── BABY ─────────────────────────────────────────────────────────────
  {
    id: "hatch-rest",
    name: "Hatch Baby Rest+ Sound Machine",
    brand: "Hatch",
    category: "Baby",
    subcategory: "Baby Sleep",
    emoji: "🌙",
    accentColor: "#7C3AED",
    price: "$89",
    trendScore: 83,
    saturationScore: 44,
    targetAudience: "New parents 26–40 struggling with infant and toddler sleep",
    description: "Smart sound machine + night light + OK-to-wake light with app control. Grows with your child from newborn to school age.",
    problem: "A baby who won't sleep — and parents running on 3 hours a night with no solution",
    uniqueAngle: "The sleep solution that grows with your child from newborn through toddler years",
    topHooks: [
      "My pediatrician recommended the Hatch. I slept 6 hours for the first time in 4 months.",
      "The OK-to-wake feature bought me back my mornings — my 2-year-old waits for the green light",
      "Hatch is what happens when you build a product for parents who are too exhausted to be skeptical",
    ],
    topAdConcepts: [
      { angle: "Desperate parent", concept: "Tired parent at 3am, Hatch routine, peaceful sleeping baby — relief in 30 seconds" },
      { angle: "Long-term value", concept: "Show the same product used from newborn → toddler → big kid sleep training" },
    ],
    competitorPositioning: "Competes against Marpac and HoMedics on white noise. Owns the smart, app-controlled, multi-age sleep training market.",
    tags: ["hatch", "sound machine", "baby sleep", "night light", "toddler", "sleep training", "ok to wake"],
    monthlySearchVolume: "380K",
    platforms: ["Amazon", "Meta", "Pinterest"],
  },
  {
    id: "owlet-sock",
    name: "Owlet Dream Sock Baby Monitor",
    brand: "Owlet",
    category: "Baby",
    subcategory: "Baby Monitor",
    emoji: "🦉",
    accentColor: "#0EA5E9",
    price: "$299",
    trendScore: 79,
    saturationScore: 40,
    targetAudience: "Anxious new parents 26–40, parents of premature babies, NICU families",
    description: "Wearable sock baby monitor tracking heart rate and oxygen levels with real-time app alerts.",
    problem: "The terrifying fear of something happening to a sleeping newborn — SIDS anxiety",
    uniqueAngle: "Peace of mind in a sock — the product that parents say is worth every penny",
    topHooks: [
      "The Owlet sock alarmed twice in our first month. Both times something was wrong.",
      "I didn't sleep for 6 weeks. Then we got the Owlet. Now I can sleep.",
      "Parents say the Owlet is the one product they'd buy before any other baby item",
    ],
    topAdConcepts: [
      { angle: "Peace of mind", concept: "Parent sleeping soundly while the sock glows green — the visual is everything" },
      { angle: "Parental testimony", concept: "Real parent testimonials about the night the alarm went off — honest and powerful" },
    ],
    competitorPositioning: "No real direct competitor. Competes against traditional baby monitors on category awareness. Wins on the fear-reduction positioning.",
    tags: ["owlet", "baby monitor", "heart rate", "oxygen", "newborn", "sids", "baby safety", "sock monitor"],
    monthlySearchVolume: "280K",
    platforms: ["Amazon", "Meta", "Pinterest"],
  },

  // ── OUTDOORS & FOOTWEAR ─────────────────────────────────────────────
  {
    id: "hoka-clifton",
    name: "Hoka Clifton 9 Running Shoes",
    brand: "Hoka",
    category: "Footwear",
    subcategory: "Running",
    emoji: "👟",
    accentColor: "#F97316",
    price: "$145",
    trendScore: 86,
    saturationScore: 58,
    targetAudience: "Runners 25–55, standing-job workers, people with joint pain or plantar fasciitis",
    description: "Maximum cushion, minimal weight running shoe. 36mm heel stack, engineered mesh upper.",
    problem: "Knee and joint pain from high-impact running, and running shoes that prioritize style over comfort",
    uniqueAngle: "The ugly shoe that turned beautiful — because performance won",
    topHooks: [
      "I have knee pain. My physical therapist told me to get Hokas. I ran a half marathon 3 months later.",
      "Hoka went from 'ugly nurses' shoe' to the coolest shoe in the world. The brand story is wild.",
      "The running shoe that orthopedic surgeons recommend — and now everyone else wants too",
    ],
    topAdConcepts: [
      { angle: "Rehabilitation to performance", concept: "Person with knee pain who went from walking to running — Hoka as the catalyst" },
      { angle: "Cushion demo", concept: "Drop test or pressure visualization showing the cushion difference vs standard running shoe" },
    ],
    competitorPositioning: "Competes against Brooks and ASICS on running performance, against On Running on style. Wins on maximum cushion and medical credibility crossover.",
    tags: ["hoka", "running shoes", "clifton", "cushion", "running", "knee pain", "plantar fasciitis", "sneakers"],
    monthlySearchVolume: "1.2M",
    platforms: ["Amazon", "Meta", "TikTok"],
  },
  {
    id: "allbirds-runners",
    name: "Allbirds Tree Runners",
    brand: "Allbirds",
    category: "Footwear",
    subcategory: "Sustainable",
    emoji: "🌱",
    accentColor: "#6EE7B7",
    price: "$135",
    trendScore: 69,
    saturationScore: 52,
    targetAudience: "Sustainability-conscious professionals 25–45, Silicon Valley culture enthusiasts",
    description: "Lightweight eucalyptus tree fiber shoes. Carbon footprint printed on each shoebox.",
    problem: "Shoes made from petroleum products in factories with no accountability — and fast fashion guilt",
    uniqueAngle: "The world's most comfortable and most sustainable shoe — proved both, not just claimed",
    topHooks: [
      "Allbirds prints their carbon footprint on the shoebox. No other brand does this.",
      "Obama wore these. Barack Obama. To the White House.",
      "The shoe brand that made sustainability a selling point instead of a trade-off",
    ],
    topAdConcepts: [
      { angle: "Transparency", concept: "Show the carbon label and explain what it means — radical honesty as the ad" },
      { angle: "Celebrity proof", concept: "Famous people who wear Allbirds — not paid, just genuinely wearing them" },
    ],
    competitorPositioning: "Competes against Veja on sustainability, against Adidas on everyday wear. Owns the Silicon Valley uniform position.",
    tags: ["allbirds", "sustainable shoes", "tree runners", "eco friendly", "carbon footprint", "eucalyptus", "sneakers"],
    monthlySearchVolume: "310K",
    platforms: ["DTC", "Meta", "Instagram"],
  },

  // ── MORE PRODUCTS ───────────────────────────────────────────────────
  {
    id: "ritual-multivitamin",
    name: "Ritual Essential Multivitamin",
    brand: "Ritual",
    category: "Supplements",
    subcategory: "Multivitamin",
    emoji: "💊",
    accentColor: "#FBBF24",
    price: "$33/mo",
    trendScore: 77,
    saturationScore: 58,
    targetAudience: "Women 25–40 who are skeptical of traditional vitamins and want ingredient transparency",
    description: "Delayed-release capsule with 9 traceable, vegan-certified ingredients. No fillers or unnecessary additives.",
    problem: "Vitamins with 30 unpronounceable fillers that you have no idea if they're actually working",
    uniqueAngle: "The vitamin that shows you exactly where every ingredient comes from",
    topHooks: [
      "Ritual publishes the farm of origin for every ingredient. I've never seen another vitamin do this.",
      "The multivitamin designed for women who think most multivitamins are a scam",
      "9 ingredients. All traceable. $33/month. That's the whole pitch.",
    ],
    topAdConcepts: [
      { angle: "Transparency story", concept: "Click through the ingredient traceability — show the actual suppliers and farms on screen" },
      { angle: "Skeptic-first", concept: "Open by validating that most vitamins are a scam — then explain why Ritual is different" },
    ],
    competitorPositioning: "Competes against One A Day and Centrum on awareness. Wins against them on ingredient quality. Competes against Thorne on medical trust.",
    tags: ["ritual", "multivitamin", "women's vitamins", "traceable", "vegan", "supplements", "transparent"],
    monthlySearchVolume: "290K",
    platforms: ["Instagram", "Meta", "Podcast"],
  },
  {
    id: "poppi-soda",
    name: "Poppi Prebiotic Soda",
    brand: "Poppi",
    category: "Food & Drink",
    subcategory: "Functional Beverage",
    emoji: "🍎",
    accentColor: "#EF4444",
    price: "$3/can",
    trendScore: 88,
    saturationScore: 57,
    targetAudience: "Health-conscious millennials and Gen Z 18–38, gut health enthusiasts, soda-reducers",
    description: "Apple cider vinegar-based prebiotic soda with real fruit juice. 25 calories, 5g prebiotic fiber.",
    problem: "The soda habit you can't quit but know you shouldn't have — and health drinks that taste like health",
    uniqueAngle: "The soda that started with a Shark Tank appearance and became a cultural moment",
    topHooks: [
      "The soda on Shark Tank that became the gut health drink of the generation",
      "25 calories, real fruit juice, prebiotics — Poppi doesn't ask you to sacrifice taste for health",
      "I switched from Diet Coke to Poppi. My gut noticed within a week.",
    ],
    topAdConcepts: [
      { angle: "Shark Tank origin story", concept: "Origin story retell with Shark Tank footage — authenticity as marketing" },
      { angle: "Taste-first", concept: "Person hesitating to try a 'healthy soda,' tasting it, immediately impressed" },
    ],
    competitorPositioning: "Direct competitor to Olipop. Both compete on prebiotic soda shelf. Poppi wins on ACV story, Olipop wins on flavor variety.",
    tags: ["poppi", "prebiotic soda", "apple cider vinegar", "gut health", "shark tank", "soda", "functional"],
    monthlySearchVolume: "390K",
    platforms: ["TikTok", "Whole Foods", "Meta"],
  },
  {
    id: "brooklinen-sheets",
    name: "Brooklinen Luxe Sateen Sheets",
    brand: "Brooklinen",
    category: "Home",
    subcategory: "Bedding",
    emoji: "🛏️",
    accentColor: "#E2E8F0",
    price: "$180/set",
    trendScore: 73,
    saturationScore: 49,
    targetAudience: "Adults 28–50 who want hotel-quality bedding without a $400 price tag",
    description: "480 thread count long-staple cotton sateen sheets. Direct-to-consumer pricing cuts out retail markup.",
    problem: "Scratchy sheets, pilling after a few washes, and paying $400 for hotel sheets that cost $40 to make",
    uniqueAngle: "DTC cuts the middleman — the same thread count as luxury hotel bedding at half the price",
    topHooks: [
      "I sleep on $180 sheets. They feel like $500 sheets. That's the DTC model.",
      "Brooklinen disrupted a $16B industry by removing the retail markup that everyone accepted as normal",
      "My hotel reviews used to say 'loved the sheets.' Now I have those sheets.",
    ],
    topAdConcepts: [
      { angle: "Hotel quality", concept: "Side-by-side of famous hotel pricing vs Brooklinen — same quality, 40% less" },
      { angle: "First sleep experience", concept: "ASMR-style reveal of new Brooklinen sheets — the sensory experience is the product" },
    ],
    competitorPositioning: "Competes against Parachute on DTC premium, against Pottery Barn on retail bedding. Wins on the DTC value narrative.",
    tags: ["brooklinen", "sheets", "bedding", "sateen", "linen", "luxury bedding", "sleep", "cotton"],
    monthlySearchVolume: "250K",
    platforms: ["Meta", "Instagram", "DTC"],
  },
];

// ── SEARCH ───────────────────────────────────────────────────────────────

export function searchProducts(query: string, limit = 8): Product[] {
  const q = query.toLowerCase().trim();
  if (!q) return [];

  return PRODUCTS
    .map((p) => {
      const name = p.name.toLowerCase();
      const brand = p.brand.toLowerCase();
      const cat = p.category.toLowerCase();
      const words = name.split(/\s+/);

      let score = 0;

      if (name === q) score += 100;
      else if (name.startsWith(q)) score += 85;
      else if (words.some((w) => w.startsWith(q))) score += 70;
      else if (name.includes(q)) score += 45;

      if (brand.startsWith(q)) score += 55;
      else if (brand.includes(q)) score += 30;

      if (cat.includes(q)) score += 20;

      if (p.tags.some((t) => t.startsWith(q))) score += 25;
      else if (p.tags.some((t) => t.includes(q))) score += 12;

      return { p, score };
    })
    .filter((x) => x.score > 0)
    .sort((a, b) => b.score - a.score || b.p.trendScore - a.p.trendScore)
    .slice(0, limit)
    .map((x) => x.p);
}

export function getProductById(id: string): Product | undefined {
  return PRODUCTS.find((p) => p.id === id);
}

export function getTrendingProducts(limit = 6): Product[] {
  return [...PRODUCTS]
    .sort((a, b) => b.trendScore - a.trendScore)
    .slice(0, limit);
}

export const TRENDING_SEARCHES = [
  "Stanley tumbler",
  "Greens powder",
  "Rare Beauty blush",
  "Air purifier",
  "Mushroom coffee",
  "Weighted blanket",
  "LED strip lights",
  "Collagen peptides",
  "Air fryer",
  "Prebiotic soda",
];

export const RECENT_SEARCHES_KEY = "ll_recent_searches";

export function getRecentSearches(): string[] {
  if (typeof window === "undefined") return [];
  try {
    return JSON.parse(localStorage.getItem(RECENT_SEARCHES_KEY) || "[]");
  } catch {
    return [];
  }
}

export function addRecentSearch(query: string) {
  if (typeof window === "undefined") return;
  const existing = getRecentSearches().filter((s) => s !== query);
  const updated = [query, ...existing].slice(0, 6);
  localStorage.setItem(RECENT_SEARCHES_KEY, JSON.stringify(updated));
}

export function clearRecentSearches() {
  if (typeof window === "undefined") return;
  localStorage.removeItem(RECENT_SEARCHES_KEY);
}
